### ISSUE TITLE
hadolint_output is empty

### ISSUE THREAD

**Issue by pascalgulikers** [jbergstroem/hadolint-gh-action#147]
```
- uses: jbergstroem/hadolint-gh-action@v1
  id: hadolint
  with:
    dockerfile: ./Dockerfile
    #output_format: sarif

- name: Debug
  shell: bash
  run: |
    echo "${{ steps.hadolint.outputs.hadolint_version }}"
    echo "${{ steps.hadolint.outputs.hadolint_gh_action_version }}"
    echo "${{ steps.hadolint.outputs.hadolint_output }}"
```
Produces:
Run echo "2.12.0"
  echo "2.12.0"
  echo "1.12.0"
  echo ""

In other words: the `hadolint_output` output variable is empty, no matter which `output_format` is specified.
It looks like it's being caused by: https://github.com/jbergstroem/hadolint-gh-action/blob/4683c5d968121c56e9488f204ee5002db792dd13/lib/main.sh#L52

Possible solution:
change
`echo "hadolint_output=${OUTPUT//$'\n'/'%0A'} >> \$GITHUB_OUTPUT"`
to
`echo "hadolint_output=${OUTPUT//$'\n'/'%0A'}" >> "${GITHUB_OUTPUT}"`
