### ISSUE TITLE
Idiomatic way to print hadolint report?

### ISSUE THREAD

**Issue by SimonSchick** [jbergstroem/hadolint-gh-action#78]
I'm trying to simple print all lint failures into the CI log rather than using annotations, mostly for consistency.

But whatever I do I can't seem to get the output to work:

```
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Lint
        id: docker-lint
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          annotate: false
          error_level: 2
          output_format: tty
          dockerfile: "**/Dockerfile"
      - name: Docker Lint Output
        if: always()
        run: echo ${{ env.OUTPUT }}
        env:
          OUTPUT: ${{ steps.docker-lint.outputs.hadolint_output }} # also tried using outputs directly in echo
```

Can you let me know if I am using this as designed or if I'm missing something here?

Btw it would be nice if the default behavior (with annotations off and no output format set) for the action to print all errors into the log rather than hiding it.
