### ISSUE TITLE
Shell expansion **/Dockerfile not finding file recursively

### ISSUE THREAD

**Issue by mloskot** [jbergstroem/hadolint-gh-action#81]
For a repo with collection of `Dockerfile`-s structured like this:
```
/a/x/Dockerfile
/a/y/Dockerfile
/a/z/Dockerfile
```

the following workflow with shell expansion

```
jobs:
  hadolint:
    name: Dockerfiles
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jbergstroem/hadolint-gh-action@v1
      with:
        dockerfile: "**/Dockerfile"
```

fails with

```
hadolint: **/Dockerfile: openBinaryFile: does not exist (No such file or directory)
```

![image](https://user-images.githubusercontent.com/80741/190997807-0d593526-bc03-4359-9668-a9fa8f9feab6.png)

Is the recursive look-up for multiple `Dockerfile`-s even supported?
I failed to find any note on that in the docs.

**Comment by jbergstroem** [comment]
Thanks for the elaborate report! The glob expansion should be working throuh the running shell; I'd call this a bug. Lets see what we can do!

**Comment by jbergstroem** [comment]
@mloskot I just opened a draft PR to address this (needs some shellcheck fixes) - perhaps you can try it and let me know how it goes? You should be able to replace `v1` with `fix/expand-glob-prior-hadolint` when using the action.

**Comment by mloskot** [comment]
@jbergstroem Thank you for light-speed quick fix. AFAICT, there is no difference:

```
jobs:
  docker:
    name: Dockerfiles
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jbergstroem/hadolint-gh-action@fix/expand-glob-prior-hadolint
      with:
        dockerfile: "**/Dockerfile"
```

![image](https://user-images.githubusercontent.com/80741/191205623-5e6373cf-96f1-4e0c-84ac-8da413c27188.png)
